# FROM microsoft/dotnet:1.1.1-sdk
FROM dotnet/dotnet-22-runtime-rhel7

WORKDIR /code

ADD src/Worker /code/src/Worker

RUN dotnet restore -v minimal src/Worker \
    && dotnet publish -c Release -o "./" "src/Worker/" 

CMD dotnet src/Worker/Worker.dll
